spring:
  application:
    name: spring_or_death
  datasource:
    url: jdbc:mysql://localhost:3306/springdb
    username: sh
    password: sh
    driver-class-name: com.mysql.cj.jdbc.Driver
    # config\uC5D0 \uC801\uC740 connection \uBD80\uBD84\uB3C4 \uC5EC\uAE30\uC5D0 \uC801\uC5B4\uC904 \uC218 \uC788\uC74C
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 50
      max-lifetime: 60000
      minimum-idle: 5 # \uB180\uACE0\uC788\uB294\uC560\uC758 \uCD5C\uB300\uAC2F\uC218
      idle-timeout: 30000
      auto-commit: false


logging:
  level:
    root: info
    com.sh: debug

server:
  servlet:
    context-path: /app
